use qltv
go
insert into TacGia (ma_tacgia, ten_tacgia) values (1, 'Bary Coppenhall');
insert into TacGia (ma_tacgia, ten_tacgia) values (2, 'Pancho Dunston');
insert into TacGia (ma_tacgia, ten_tacgia) values (3, 'Dov Meffen');
insert into TacGia (ma_tacgia, ten_tacgia) values (4, 'Tobit Byforth');
insert into TacGia (ma_tacgia, ten_tacgia) values (5, 'Jaye Teaz');
insert into TacGia (ma_tacgia, ten_tacgia) values (6, 'Juliana Archdeacon');
insert into TacGia (ma_tacgia, ten_tacgia) values (7, 'Anni Aimable');
insert into TacGia (ma_tacgia, ten_tacgia) values (8, 'Corette Sans');
insert into TacGia (ma_tacgia, ten_tacgia) values (9, 'Laurie Cicchinelli');
insert into TacGia (ma_tacgia, ten_tacgia) values (10, 'Fredia Pavlishchev');
insert into TacGia (ma_tacgia, ten_tacgia) values (11, 'Rhianna Stapley');
insert into TacGia (ma_tacgia, ten_tacgia) values (12, 'Dunstan Plevin');
insert into TacGia (ma_tacgia, ten_tacgia) values (13, 'Dew Napolitano');
insert into TacGia (ma_tacgia, ten_tacgia) values (14, 'Catlee Mussen');
insert into TacGia (ma_tacgia, ten_tacgia) values (15, 'Von Zold');
insert into TacGia (ma_tacgia, ten_tacgia) values (16, 'Eachelle Jako');
insert into TacGia (ma_tacgia, ten_tacgia) values (17, 'Isidor Bedburrow');
insert into TacGia (ma_tacgia, ten_tacgia) values (18, 'Lynelle Conford');
insert into TacGia (ma_tacgia, ten_tacgia) values (19, 'Doretta Cadden');
insert into TacGia (ma_tacgia, ten_tacgia) values (20, 'Daisie Mapletoft');
insert into TacGia (ma_tacgia, ten_tacgia) values (21, 'Deina Jenkyn');
insert into TacGia (ma_tacgia, ten_tacgia) values (22, 'Alleyn Angear');
insert into TacGia (ma_tacgia, ten_tacgia) values (23, 'Hadria Alessandrucci');
insert into TacGia (ma_tacgia, ten_tacgia) values (24, 'Fields Amaya');
insert into TacGia (ma_tacgia, ten_tacgia) values (25, 'Geneva Messruther');
insert into TacGia (ma_tacgia, ten_tacgia) values (26, 'Eden Ply');
insert into TacGia (ma_tacgia, ten_tacgia) values (27, 'Jodie MacGaughie');
insert into TacGia (ma_tacgia, ten_tacgia) values (28, 'Towny Tumbridge');
insert into TacGia (ma_tacgia, ten_tacgia) values (29, 'Benedetto Eddie');
insert into TacGia (ma_tacgia, ten_tacgia) values (30, 'Kevin Edgin');
insert into TacGia (ma_tacgia, ten_tacgia) values (31, 'Krystalle Dyball');
insert into TacGia (ma_tacgia, ten_tacgia) values (32, 'Eal Rathke');
insert into TacGia (ma_tacgia, ten_tacgia) values (33, 'Joell Godfray');
insert into TacGia (ma_tacgia, ten_tacgia) values (34, 'Knox Wasylkiewicz');
insert into TacGia (ma_tacgia, ten_tacgia) values (35, 'Konstantin Uphill');
insert into TacGia (ma_tacgia, ten_tacgia) values (36, 'Jilly Murt');
insert into TacGia (ma_tacgia, ten_tacgia) values (37, 'Sosanna Berrycloth');
insert into TacGia (ma_tacgia, ten_tacgia) values (38, 'Daffie Jedrzej');
insert into TacGia (ma_tacgia, ten_tacgia) values (39, 'Vanny Caesmans');
insert into TacGia (ma_tacgia, ten_tacgia) values (40, 'Damaris Luttgert');
insert into TacGia (ma_tacgia, ten_tacgia) values (41, 'Dolf Huckerbe');
insert into TacGia (ma_tacgia, ten_tacgia) values (42, 'Tessie Bentjens');
insert into TacGia (ma_tacgia, ten_tacgia) values (43, 'Hugo Handasyde');
insert into TacGia (ma_tacgia, ten_tacgia) values (44, 'Somerset Zecchi');
insert into TacGia (ma_tacgia, ten_tacgia) values (45, 'Abner House');
insert into TacGia (ma_tacgia, ten_tacgia) values (46, 'Amalia Cominello');
insert into TacGia (ma_tacgia, ten_tacgia) values (47, 'Heinrik McRobb');
insert into TacGia (ma_tacgia, ten_tacgia) values (48, 'Victoria Breche');
insert into TacGia (ma_tacgia, ten_tacgia) values (49, 'Fianna Forbear');
insert into TacGia (ma_tacgia, ten_tacgia) values (50, 'Devland Slafford');
insert into TacGia (ma_tacgia, ten_tacgia) values (51, 'Rebeca Jeandeau');
insert into TacGia (ma_tacgia, ten_tacgia) values (52, 'Aubrey Foulkes');
insert into TacGia (ma_tacgia, ten_tacgia) values (53, 'Hyman Lalley');
insert into TacGia (ma_tacgia, ten_tacgia) values (54, 'Brittan Tritton');
insert into TacGia (ma_tacgia, ten_tacgia) values (55, 'Kriste Paute');
insert into TacGia (ma_tacgia, ten_tacgia) values (56, 'Graeme Torri');
insert into TacGia (ma_tacgia, ten_tacgia) values (57, 'Lelia Simonitto');
insert into TacGia (ma_tacgia, ten_tacgia) values (58, 'Mildred Mariolle');
insert into TacGia (ma_tacgia, ten_tacgia) values (59, 'Percival Puddin');
insert into TacGia (ma_tacgia, ten_tacgia) values (60, 'Cilka O''Cannan');
insert into TacGia (ma_tacgia, ten_tacgia) values (61, 'Kev Nalder');
insert into TacGia (ma_tacgia, ten_tacgia) values (62, 'Dunstan Langeren');
insert into TacGia (ma_tacgia, ten_tacgia) values (63, 'Richy Gallegos');
insert into TacGia (ma_tacgia, ten_tacgia) values (64, 'Efren Pindar');
insert into TacGia (ma_tacgia, ten_tacgia) values (65, 'Ruben Saket');
insert into TacGia (ma_tacgia, ten_tacgia) values (66, 'Cher Amesbury');
insert into TacGia (ma_tacgia, ten_tacgia) values (67, 'Laurie Janning');
insert into TacGia (ma_tacgia, ten_tacgia) values (68, 'Reinaldos Greedy');
insert into TacGia (ma_tacgia, ten_tacgia) values (69, 'Hadria Brittoner');
insert into TacGia (ma_tacgia, ten_tacgia) values (70, 'Brena Suttell');
insert into TacGia (ma_tacgia, ten_tacgia) values (71, 'Beverley Cundey');
insert into TacGia (ma_tacgia, ten_tacgia) values (72, 'Johna Gregh');
insert into TacGia (ma_tacgia, ten_tacgia) values (73, 'Lucila Iiannone');
insert into TacGia (ma_tacgia, ten_tacgia) values (74, 'Maureen Laugier');
insert into TacGia (ma_tacgia, ten_tacgia) values (75, 'Ivan Ranfield');
insert into TacGia (ma_tacgia, ten_tacgia) values (76, 'Aubrette Pharoah');
insert into TacGia (ma_tacgia, ten_tacgia) values (77, 'Lark Heliet');
insert into TacGia (ma_tacgia, ten_tacgia) values (78, 'Ursulina Dix');
insert into TacGia (ma_tacgia, ten_tacgia) values (79, 'Blondy Dugall');
insert into TacGia (ma_tacgia, ten_tacgia) values (80, 'Cordie Crosswaite');
insert into TacGia (ma_tacgia, ten_tacgia) values (81, 'Agneta Tinman');
insert into TacGia (ma_tacgia, ten_tacgia) values (82, 'Avie Maccrie');
insert into TacGia (ma_tacgia, ten_tacgia) values (83, 'Merle Saltsberger');
insert into TacGia (ma_tacgia, ten_tacgia) values (84, 'Ken Toulmin');
insert into TacGia (ma_tacgia, ten_tacgia) values (85, 'Portia Mahody');
insert into TacGia (ma_tacgia, ten_tacgia) values (86, 'Dru Edlington');
insert into TacGia (ma_tacgia, ten_tacgia) values (87, 'Berny Atcherley');
insert into TacGia (ma_tacgia, ten_tacgia) values (88, 'Nerte O'' Meara');
insert into TacGia (ma_tacgia, ten_tacgia) values (89, 'Marietta Foxen');
insert into TacGia (ma_tacgia, ten_tacgia) values (90, 'Lauraine Haslum');
insert into TacGia (ma_tacgia, ten_tacgia) values (91, 'Giuditta Goodwin');
insert into TacGia (ma_tacgia, ten_tacgia) values (92, 'Rochella Benfield');
insert into TacGia (ma_tacgia, ten_tacgia) values (93, 'Idelle Peartree');
insert into TacGia (ma_tacgia, ten_tacgia) values (94, 'Myrtie Kapelhoff');
insert into TacGia (ma_tacgia, ten_tacgia) values (95, 'Amara Honeywood');
insert into TacGia (ma_tacgia, ten_tacgia) values (96, 'Bobbi Kelling');
insert into TacGia (ma_tacgia, ten_tacgia) values (97, 'Aridatha Ledley');
insert into TacGia (ma_tacgia, ten_tacgia) values (98, 'Giordano Deaville');
insert into TacGia (ma_tacgia, ten_tacgia) values (99, 'Leola Osman');
insert into TacGia (ma_tacgia, ten_tacgia) values (100, 'Marna Nerval');
go
insert into LoaiTaiLieu (ma_loai, ten_loai) values ('sach', 'Sach');
insert into LoaiTaiLieu (ma_loai, ten_loai) values ('dia', 'CD/DVD')
insert into LoaiTaiLieu (ma_loai, ten_loai) values ('LA', 'Luan An')
insert into LoaiTaiLieu (ma_loai, ten_loai) values ('tapchi', 'Tap Chi')
go
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (1, 7, 13, NULL, 'dia', 'Nga', 'Mem', 'Y', 83000, 'Statoil ASA', 0, '2003/11/12');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (2, 26, NULL, NULL, 'sach', 'Trung', 'Cung', 'Y', 203000, 'Targa Resources, Inc.', 0, '2006/10/13');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (3, 86, 10, NULL, 'dia', 'Anh', NULL, 'Y', 905000, 'Regency Centers Corporation', 0, '2007/12/25');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (4, 88, 97, NULL, 'LA', 'Trung', 'Lua', 'Y', 829000, 'Mastercard Incorporated', 0, '2008/01/19');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (5, 95, 37, 77, 'tapchi', 'Nga', 'Cung', 'Y', 815000, 'Astoria Financial Corporation', 0, '2003/12/23');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (6, 13, 80, NULL, 'dia', 'Nga', 'Mem', 'Y', 678000, 'Intellipharmaceutics International Inc.', 0, '2002/01/26');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (7, 77, 5, NULL, 'LA', 'Anh', NULL, 'Y', 658000, 'China Zenix Auto International Limited', 0, '2011/06/11');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (8, 52, NULL, 46, 'sach', 'Nhat', 'Mem', 'Y', 685000, 'Sorrento Therapeutics, Inc.', 0, '2016/12/24');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (9, 46, NULL, 50, 'tapchi', 'Nga', 'Lua', 'Y', 363000, 'United Technologies Corporation', 0, '1994/07/03');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (10, 6, 55, NULL, 'LA', 'Nhat', 'Cung', 'Y', 806000, 'Lee Enterprises, Incorporated', 0, '2010/11/18');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (11, 11, NULL, NULL, 'dia', 'Nhat', NULL, 'Y', 599000, 'LiNiu Technology Group', 0, '2006/04/11');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (12, 58, 35, NULL, 'dia', 'Trung', 'Lua', 'Y', 857000, 'Golden Entertainment, Inc.', 0, '2015/01/30');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (13, 74, NULL, NULL, 'tapchi', 'Anh', 'Mem', 'Y', 145000, 'M/I Homes, Inc.', 0, '2007/05/14');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (14, 58, 72, NULL, 'tapchi', 'Viet', 'Cung', 'Y', 942000, 'F.N.B. Corporation', 0, '2010/03/27');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (15, 33, NULL, NULL, 'LA', 'Anh', 'Cung', 'Y', 674000, 'Arcadia Biosciences, Inc.', 0, '1990/09/10');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (16, 62, NULL, 40, 'dia', 'Viet', 'Lua', 'Y', 710000, 'Entertainment Gaming Asia Incorporated', 0, '2009/04/17');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (17, 16, NULL, NULL, 'LA', 'Nga', 'Mem', 'Y', 551000, 'RigNet, Inc.', 0, '1996/04/21');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (18, 39, 99, NULL, 'tapchi', 'Nga', 'Cung', 'Y', 873000, 'INVESCO MORTGAGE CAPITAL INC', 0, '2005/05/27');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (19, 41, 54, NULL, 'LA', 'Trung', 'Mem', 'Y', 699000, 'Mobile Mini, Inc.', 0, '2010/05/29');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (20, 47, 41, 46, 'tapchi', 'Nhat', 'Lua', 'Y', 179000, 'NBT Bancorp Inc.', 0, '2004/02/27');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (21, 73, NULL, NULL, 'LA', 'Nga', 'Lua', 'Y', 516000, 'X-Links Silver Shares Covered Call ETN', 0, '2001/07/07');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (22, 20, 68, NULL, 'LA', 'Anh', NULL, 'Y', 900000, 'MV Oil Trust', 0, '1995/01/24');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (23, 3, 68, 40, 'LA', 'Nhat', 'Cung', 'Y', 458000, 'BGC Partners, Inc.', 0, '1994/09/26');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (24, 31, NULL, NULL, 'dia', 'Viet', 'Cung', 'Y', 421000, 'Liberty Global plc', 0, '1994/03/06');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (25, 61, 76, NULL, 'tapchi', 'Nga', 'Lua', 'Y', 66000, 'Algonquin Power & Utilities Corp.', 0, '1990/06/01');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (26, 15, 61, NULL, 'LA', 'Nga', 'Cung', 'Y', 174000, 'Bank of Commerce Holdings (CA)', 0, '2018/02/12');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (27, 26, NULL, 76, 'sach', 'Anh', 'Mem', 'Y', 240000, 'Celyad SA', 0, '1994/04/10');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (28, 18, NULL, 25, 'tapchi', 'Viet', 'Lua', 'Y', 300000, 'Smart Sand, Inc.', 0, '2012/01/29');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (29, 6, 68, NULL, 'sach', 'Nhat', 'Mem', 'Y', 243000, 'Prudential Financial, Inc.', 0, '2018/04/17');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (30, 9, 85, NULL, 'sach', 'Trung', 'Lua', 'Y', 781000, 'Odyssey Marine Exploration, Inc.', 0, '1992/08/02');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (31, 34, NULL, 32, 'LA', 'Nga', 'Cung', 'Y', 516000, 'Nanometrics Incorporated', 0, '1996/08/04');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (32, 88, NULL, NULL, 'LA', 'Anh', 'Cung', 'Y', 680000, 'Firsthand Technology Value Fund, Inc.', 0, '2004/01/08');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (33, 94, 50, NULL, 'sach', 'Anh', 'Mem', 'Y', 738000, 'Pingtan Marine Enterprise Ltd.', 0, '1990/09/17');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (34, 5, NULL, NULL, 'dia', 'Nhat', 'Lua', 'Y', 54000, 'America''s Car-Mart, Inc.', 0, '2012/01/31');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (35, 18, NULL, NULL, 'sach', 'Nhat', 'Mem', 'Y', 660000, 'GDS Holdings Limited', 0, '2003/07/29');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (36, 50, 18, NULL, 'dia', 'Trung', 'Cung', 'Y', 314000, 'Rosehill Resources Inc.', 0, '1997/02/17');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (37, 6, NULL, NULL, 'LA', 'Anh', 'Cung', 'Y', 425000, 'Syndax Pharmaceuticals, Inc.', 0, '2004/03/13');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (38, 70, 48, NULL, 'sach', 'Viet', 'Mem', 'Y', 90000, 'Gladstone Capital Corporation', 0, '1991/06/18');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (39, 16, 53, NULL, 'LA', 'Trung', NULL, 'Y', 715000, 'Wells Fargo & Company', 0, '1991/05/21');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (40, 55, NULL, NULL, 'LA', 'Anh', 'Lua', 'Y', 938000, 'Eldorado Gold Corporation', 0, '1992/08/25');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (41, 71, 55, NULL, 'LA', 'Anh', 'Lua', 'Y', 578000, 'Aqua America, Inc.', 0, '1991/06/10');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (42, 22, NULL, NULL, 'dia', 'Anh', NULL, 'Y', 134000, 'Kratos Defense & Security Solutions, Inc.', 0, '2018/04/12');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (43, 70, 73, NULL, 'dia', 'Anh', 'Mem', 'Y', 210000, 'Altisource Portfolio Solutions S.A.', 0, '2006/05/06');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (44, 17, 60, NULL, 'dia', 'Anh', NULL, 'Y', 929000, 'Hilton Grand Vacations Inc.', 0, '1991/03/12');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (45, 94, 84, 7, 'sach', 'Nga', 'Mem', 'Y', 939000, 'SB Financial Group, Inc.', 0, '2005/03/19');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (46, 83, 69, NULL, 'LA', 'Trung', NULL, 'Y', 681000, 'Connecture, Inc.', 0, '2009/12/09');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (47, 43, 44, 21, 'dia', 'Anh', 'Cung', 'Y', 482000, 'Ares Capital Corporation', 0, '2008/01/11');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (48, 62, NULL, 32, 'sach', 'Nhat', 'Mem', 'Y', 464000, 'TTM Technologies, Inc.', 0, '1998/10/23');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (49, 68, 12, NULL, 'dia', 'Nhat', 'Cung', 'Y', 881000, 'One Liberty Properties, Inc.', 0, '2002/07/13');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (50, 47, NULL, NULL, 'tapchi', 'Nga', NULL, 'Y', 365000, 'Bank of America Corporation', 0, '1990/03/17');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (51, 12, 28, NULL, 'tapchi', 'Nga', NULL, 'Y', 397000, 'Origo Acquisition Corporation', 0, '1990/05/07');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (52, 36, 48, NULL, 'LA', 'Anh', NULL, 'Y', 129000, 'Chesapeake Lodging Trust', 0, '2006/11/27');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (53, 32, NULL, NULL, 'sach', 'Viet', 'Lua', 'Y', 240000, 'Lincoln Electric Holdings, Inc.', 0, '2001/11/15');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (54, 81, 77, NULL, 'LA', 'Anh', 'Cung', 'Y', 817000, 'Beneficial Bancorp, Inc.', 0, '1994/09/02');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (55, 57, 27, NULL, 'LA', 'Nhat', NULL, 'Y', 213000, 'E.I. du Pont de Nemours and Company', 0, '1994/09/25');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (56, 13, 54, NULL, 'tapchi', 'Nhat', 'Lua', 'Y', 122000, 'Gladstone Capital Corporation', 0, '2010/12/31');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (57, 82, 34, 87, 'dia', 'Anh', 'Mem', 'Y', 924000, 'DAVIDsTEA Inc.', 0, '1999/03/21');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (58, 12, 54, 57, 'dia', 'Nga', 'Mem', 'Y', 957000, 'Monster Beverage Corporation', 0, '2005/01/21');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (59, 35, 3, NULL, 'tapchi', 'Trung', 'Lua', 'Y', 577000, 'Natural Health Trends Corp.', 0, '2004/02/03');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (60, 43, 60, NULL, 'sach', 'Nhat', 'Mem', 'Y', 825000, 'Marin Software Incorporated', 0, '2013/12/21');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (61, 77, NULL, NULL, 'tapchi', 'Anh', NULL, 'Y', 332000, 'Blackrock MuniVest Fund II, Inc.', 0, '2000/10/19');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (62, 94, NULL, NULL, 'dia', 'Trung', 'Cung', 'Y', 749000, 'Griffin Industrial Realty, Inc.', 0, '1997/12/08');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (63, 35, NULL, NULL, 'sach', 'Nga', 'Mem', 'Y', 632000, 'Alon USA Energy, Inc.', 0, '1994/01/22');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (64, 40, 65, NULL, 'dia', 'Trung', 'Lua', 'Y', 825000, 'Horizons DAX Germany ETF', 0, '2002/07/22');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (65, 13, NULL, 25, 'LA', 'Nga', 'Mem', 'Y', 418000, 'Cabot Oil & Gas Corporation', 0, '1999/06/04');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (66, 30, 93, NULL, 'dia', 'Nga', 'Cung', 'Y', 330000, 'Tortoise Power and Energy Infrastructure Fund, Inc', 0, '2005/01/29');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (67, 56, 71, NULL, 'tapchi', 'Anh', 'Lua', 'Y', 182000, 'Barclays Inverse US Treasury Composite ETN', 0, '1993/07/01');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (68, 2, 29, NULL, 'LA', 'Nga', 'Cung', 'Y', 697000, 'Poage Bankshares, Inc.', 0, '1993/03/21');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (69, 85, 32, NULL, 'dia', 'Nhat', 'Lua', 'Y', 233000, 'AmeriGas Partners, L.P.', 0, '2007/08/16');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (70, 55, 61, NULL, 'LA', 'Anh', 'Mem', 'Y', 162000, 'Silver Spring Networks, Inc.', 0, '1992/07/06');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (71, 99, NULL, NULL, 'tapchi', 'Viet', 'Lua', 'Y', 834000, 'InVivo Therapeutics Holdings Corp.', 0, '2011/10/29');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (72, 84, NULL, NULL, 'tapchi', 'Viet', NULL, 'Y', 190000, 'Granite Real Estate Inc.', 0, '2007/06/05');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (73, 61, 94, NULL, 'sach', 'Nga', NULL, 'Y', 216000, 'Wellesley Bancorp, Inc.', 0, '1991/07/16');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (74, 52, NULL, 77, 'tapchi', 'Viet', 'Mem', 'Y', 233000, 'Tellurian Inc.', 0, '2017/03/17');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (75, 39, 76, NULL, 'LA', 'Anh', 'Lua', 'Y', 178000, 'Netshoes (Cayman) Limited', 0, '1996/07/17');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (76, 67, NULL, 26, 'sach', 'Trung', NULL, 'Y', 666000, 'Capitol Federal Financial, Inc.', 0, '1993/06/07');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (77, 36, NULL, NULL, 'sach', 'Nhat', 'Mem', 'Y', 502000, 'Royal Bank Scotland plc (The)', 0, '2008/07/13');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (78, 47, NULL, NULL, 'sach', 'Anh', 'Mem', 'Y', 947000, 'Avnet, Inc.', 0, '1991/07/23');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (79, 55, 67, NULL, 'tapchi', 'Anh', NULL, 'Y', 585000, 'Brookfield Infrastructure Partners LP', 0, '2003/12/24');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (80, 72, NULL, 72, 'LA', 'Trung', 'Cung', 'Y', 847000, 'Mastercard Incorporated', 0, '1991/10/26');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (81, 79, NULL, 46, 'LA', 'Trung', 'Cung', 'Y', 859000, 'Ardagh Group S.A.', 0, '1992/06/14');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (82, 68, 11, NULL, 'tapchi', 'Viet', 'Lua', 'Y', 55000, 'Celsius Holdings, Inc.', 0, '1996/04/08');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (83, 73, 2, NULL, 'LA', 'Viet', 'Mem', 'Y', 756000, 'Broadcom Limited', 0, '2009/08/09');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (84, 76, 68, NULL, 'LA', 'Nga', 'Lua', 'Y', 385000, 'BlackRock 2022 Global Income Opportunity Trust', 0, '2001/10/31');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (85, 19, 26, 79, 'tapchi', 'Anh', 'Mem', 'Y', 964000, 'Ciner Resources LP', 0, '2006/06/15');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (86, 11, NULL, 58, 'tapchi', 'Trung', 'Cung', 'Y', 275000, 'Pimco New York Municipal Income Fund II', 0, '2018/04/29');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (87, 44, NULL, NULL, 'LA', 'Nga', 'Lua', 'Y', 641000, 'Duff & Phelps Global Utility Income Fund Inc.', 0, '1998/08/22');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (88, 42, 81, 68, 'dia', 'Viet', 'Mem', 'Y', 899000, 'Pangaea Logistics Solutions Ltd.', 0, '1998/09/22');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (89, 48, NULL, NULL, 'sach', 'Nga', 'Cung', 'Y', 716000, 'Cementos Pacasmayo S.A.A.', 0, '1996/09/13');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (90, 65, NULL, NULL, 'dia', 'Anh', 'Mem', 'Y', 286000, 'Neenah Paper, Inc.', 0, '2000/08/02');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (91, 92, NULL, NULL, 'sach', 'Nhat', 'Lua', 'Y', 998000, 'The Spectranetics Corporation', 0, '2010/11/01');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (92, 30, 37, 20, 'dia', 'Nhat', 'Mem', 'Y', 878000, 'AAR Corp.', 0, '1999/11/18');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (93, 16, 64, NULL, 'tapchi', 'Anh', NULL, 'Y', 578000, 'LightPath Technologies, Inc.', 0, '2018/04/11');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (94, 40, 94, NULL, 'sach', 'Anh', 'Lua', 'Y', 921000, 'Caesars Entertainment Corporation', 0, '1999/02/04');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (95, 37, NULL, NULL, 'LA', 'Nga', 'Lua', 'Y', 903000, 'RLI Corp.', 0, '2003/08/26');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (96, 70, NULL, NULL, 'tapchi', 'Viet', 'Mem', 'Y', 999000, 'Zumiez Inc.', 0, '1998/04/23');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (97, 27, NULL, NULL, 'sach', 'Nhat', 'Mem', 'Y', 815000, 'Puma Biotechnology Inc', 0, '2006/03/24');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (98, 78, 15, NULL, 'tapchi', 'Anh', 'Mem', 'Y', 534000, 'Codexis, Inc.', 0, '2012/12/23');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (99, 74, 73, 93, 'dia', 'Nhat', 'Lua', 'Y', 204000, 'Tronox Limited', 0, '2006/01/26');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (100, 47, NULL, NULL, 'LA', 'Nga', 'Mem', 'Y', 94000, 'Arrow DWA Tactical ETF', 0, '1999/01/28');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (101, 30, 33, NULL, 'sach', 'Nhat', 'Cung', 'Y', 74000, 'Huntington Bancshares Incorporated', 0, '2006/06/13');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (102, 44, 52, NULL, 'dia', 'Nga', 'Lua', 'Y', 537000, 'A.H. Belo Corporation', 0, '1997/11/17');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (103, 61, NULL, 67, 'tapchi', 'Trung', 'Cung', 'Y', 841000, 'E*TRADE Financial Corporation', 0, '1994/06/06');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (104, 79, 16, NULL, 'sach', 'Trung', 'Mem', 'Y', 689000, 'Tempur Sealy International, Inc.', 0, '2002/04/26');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (105, 41, 55, NULL, 'tapchi', 'Anh', 'Cung', 'Y', 252000, 'Berkshire Hathaway Inc.', 0, '2003/04/24');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (106, 1, 68, NULL, 'LA', 'Viet', 'Lua', 'Y', 403000, 'GATX Corporation', 0, '2018/05/14');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (107, 94, 60, NULL, 'tapchi', 'Anh', 'Cung', 'Y', 179000, 'Hostess Brands, Inc.', 0, '2002/07/06');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (108, 32, NULL, NULL, 'LA', 'Nga', 'Cung', 'Y', 583000, 'Hersha Hospitality Trust', 0, '1998/10/22');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (109, 17, NULL, 44, 'sach', 'Anh', 'Cung', 'Y', 785000, 'Maximus, Inc.', 0, '1998/10/09');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (110, 81, 49, NULL, 'LA', 'Nga', 'Mem', 'Y', 269000, 'Flexsteel Industries, Inc.', 0, '2013/11/21');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (111, 24, 70, NULL, 'dia', 'Anh', 'Lua', 'Y', 316000, 'Allstate Corporation (The)', 0, '2007/11/04');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (112, 22, 93, NULL, 'sach', 'Viet', 'Lua', 'Y', 144000, 'Advanced Emissions Solutions, Inc.', 0, '2019/05/27');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (113, 50, NULL, NULL, 'LA', 'Nhat', NULL, 'Y', 802000, 'Pimco Corporate & Income Opportunity Fund', 0, '1999/01/21');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (114, 95, 75, NULL, 'dia', 'Nhat', 'Mem', 'Y', 380000, 'Blue Buffalo Pet Products, Inc.', 0, '1996/12/23');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (115, 5, 86, NULL, 'sach', 'Anh', NULL, 'Y', 742000, 'Virco Manufacturing Corporation', 0, '1991/06/21');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (116, 45, NULL, NULL, 'dia', 'Anh', NULL, 'Y', 957000, 'Digi International Inc.', 0, '1994/03/12');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (117, 10, 37, NULL, 'sach', 'Nga', 'Lua', 'Y', 296000, 'AAON, Inc.', 0, '2013/04/27');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (118, 95, NULL, NULL, 'tapchi', 'Nhat', 'Mem', 'Y', 494000, 'Weatherford International plc', 0, '2005/10/15');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (119, 39, NULL, 41, 'LA', 'Nga', NULL, 'Y', 563000, 'Washington Trust Bancorp, Inc.', 0, '2004/12/08');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (120, 2, NULL, 22, 'dia', 'Trung', 'Cung', 'Y', 616000, 'ESSA Bancorp, Inc.', 0, '1995/07/24');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (121, 17, 32, 77, 'sach', 'Anh', 'Lua', 'Y', 503000, 'Garmin Ltd.', 0, '2011/12/25');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (122, 33, 1, NULL, 'tapchi', 'Viet', 'Mem', 'Y', 211000, 'Lyon William Homes', 0, '2017/11/25');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (123, 27, 74, NULL, 'LA', 'Viet', 'Mem', 'Y', 741000, 'Reinsurance Group of America, Incorporated', 0, '2010/11/10');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (124, 25, NULL, NULL, 'sach', 'Viet', NULL, 'Y', 659000, 'Fidus Investment Corporation', 0, '2016/01/06');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (125, 43, NULL, 59, 'sach', 'Nhat', 'Cung', 'Y', 675000, 'Cohen & Steers Quality Income Realty Fund Inc', 0, '2019/02/21');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (126, 63, 42, NULL, 'tapchi', 'Nhat', 'Mem', 'Y', 264000, 'Galena Biopharma, Inc.', 0, '1991/10/03');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (127, 73, NULL, NULL, 'dia', 'Trung', 'Mem', 'Y', 568000, 'American Homes 4 Rent', 0, '2013/11/29');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (128, 23, 42, NULL, 'tapchi', 'Anh', 'Lua', 'Y', 219000, 'Leading Brands Inc', 0, '1996/07/31');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (129, 29, 92, 84, 'sach', 'Nga', NULL, 'Y', 572000, 'GTx, Inc.', 0, '1997/06/17');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (130, 34, NULL, NULL, 'LA', 'Nhat', 'Mem', 'Y', 437000, 'Endurance Specialty Holdings Ltd', 0, '1992/06/23');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (131, 65, 77, 63, 'LA', 'Nga', 'Mem', 'Y', 444000, 'American Homes 4 Rent', 0, '2009/09/30');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (132, 67, NULL, 8, 'dia', 'Viet', 'Mem', 'Y', 960000, 'Central Federal Corporation', 0, '1992/07/20');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (133, 64, NULL, NULL, 'dia', 'Anh', 'Mem', 'Y', 385000, 'VictoryShares Emerging Market Volatility Wtd ETF', 0, '2012/01/04');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (134, 14, NULL, NULL, 'LA', 'Nhat', NULL, 'Y', 792000, 'MS Income Securities, Inc.', 0, '2009/04/28');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (135, 8, NULL, 77, 'tapchi', 'Anh', 'Lua', 'Y', 644000, 'Multi-Color Corporation', 0, '2015/11/19');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (136, 93, 7, NULL, 'LA', 'Trung', NULL, 'Y', 363000, 'HP Inc.', 0, '2000/03/06');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (137, 81, NULL, NULL, 'sach', 'Nhat', 'Cung', 'Y', 203000, 'Arrow Financial Corporation', 0, '1993/02/25');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (138, 100, NULL, 44, 'tapchi', 'Nga', 'Mem', 'Y', 435000, 'VCA Inc. ', 0, '2007/02/24');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (139, 91, NULL, NULL, 'sach', 'Nga', 'Mem', 'Y', 222000, 'Galectin Therapeutics Inc.', 0, '2006/12/05');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (140, 56, 43, 85, 'tapchi', 'Trung', NULL, 'Y', 705000, 'Jaguar Animal Health, Inc.', 0, '2003/12/05');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (141, 28, 84, NULL, 'dia', 'Trung', 'Mem', 'Y', 684000, 'Williams Partners LP', 0, '1992/10/22');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (142, 78, 80, NULL, 'LA', 'Nga', 'Cung', 'Y', 151000, 'Aimmune Therapeutics, Inc.', 0, '1999/06/20');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (143, 68, 14, NULL, 'tapchi', 'Trung', NULL, 'Y', 368000, 'Clean Harbors, Inc.', 0, '2010/08/21');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (144, 66, NULL, NULL, 'tapchi', 'Nga', 'Lua', 'Y', 832000, 'STAAR Surgical Company', 0, '2016/04/23');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (145, 83, NULL, 28, 'LA', 'Viet', 'Cung', 'Y', 574000, 'Costamare Inc.', 0, '1996/09/21');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (146, 81, 58, NULL, 'tapchi', 'Nga', 'Mem', 'Y', 322000, 'PerkinElmer, Inc.', 0, '2000/12/05');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (147, 95, NULL, NULL, 'tapchi', 'Nhat', 'Cung', 'Y', 69000, 'Arconic Inc.', 0, '2012/02/20');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (148, 88, NULL, NULL, 'sach', 'Nga', NULL, 'Y', 981000, 'LPL Financial Holdings Inc.', 0, '2008/08/12');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (149, 76, 80, NULL, 'LA', 'Anh', 'Cung', 'Y', 19000, 'Strongbridge Biopharma plc', 0, '2004/04/03');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (150, 47, 70, NULL, 'sach', 'Nhat', NULL, 'Y', 167000, 'Alexander''s, Inc.', 0, '1990/06/30');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (151, 92, NULL, NULL, 'tapchi', 'Viet', 'Cung', 'Y', 625000, 'FCB Financial Holdings, Inc.', 0, '1992/10/20');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (152, 26, 39, NULL, 'tapchi', 'Nhat', 'Cung', 'Y', 85000, 'Dun & Bradstreet Corporation (The)', 0, '1999/09/24');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (153, 62, NULL, NULL, 'LA', 'Trung', NULL, 'Y', 440000, 'Bank Of Montreal', 0, '1999/02/10');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (154, 75, NULL, NULL, 'sach', 'Trung', 'Mem', 'Y', 469000, 'Lannett Co Inc', 0, '2004/07/13');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (155, 37, 54, NULL, 'sach', 'Trung', 'Mem', 'Y', 780000, 'Vanguard Long-Term Government Bond ETF', 0, '2006/09/23');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (156, 7, 84, NULL, 'sach', 'Nga', NULL, 'Y', 140000, 'Mammoth Energy Services, Inc.', 0, '2007/06/08');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (157, 54, NULL, NULL, 'LA', 'Viet', 'Mem', 'Y', 423000, 'Methanex Corporation', 0, '2009/04/29');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (158, 67, NULL, 26, 'sach', 'Nhat', 'Mem', 'Y', 128000, 'Superior Uniform Group, Inc.', 0, '2015/02/19');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (159, 74, 33, NULL, 'sach', 'Viet', 'Cung', 'Y', 430000, 'Citigroup Inc.', 0, '2017/05/23');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (160, 53, NULL, NULL, 'LA', 'Nhat', NULL, 'Y', 251000, 'Pacific Special Acquisition Corp.', 0, '1990/09/09');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (161, 11, 95, NULL, 'LA', 'Viet', 'Mem', 'Y', 709000, 'Seneca Foods Corp.', 0, '1999/11/25');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (162, 99, 34, NULL, 'sach', 'Nga', NULL, 'Y', 435000, 'Cincinnati Bell Inc', 0, '2000/03/03');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (163, 33, 84, NULL, 'sach', 'Nhat', 'Lua', 'Y', 237000, 'Goldman Sachs Group, Inc. (The)', 0, '1999/11/27');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (164, 87, 20, NULL, 'tapchi', 'Trung', NULL, 'Y', 454000, 'CardConnect Corp.', 0, '2000/03/10');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (165, 46, 10, NULL, 'sach', 'Trung', NULL, 'Y', 632000, 'Jaguar Animal Health, Inc.', 0, '2006/01/23');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (166, 94, 100, 49, 'tapchi', 'Nga', 'Lua', 'Y', 363000, 'FireEye, Inc.', 0, '2003/03/21');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (167, 94, NULL, NULL, 'LA', 'Anh', 'Cung', 'Y', 197000, 'Trupanion, Inc.', 0, '2013/10/18');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (168, 44, 10, NULL, 'tapchi', 'Viet', 'Mem', 'Y', 63000, 'Sprott Focus Trust, Inc.', 0, '2000/08/12');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (169, 100, NULL, NULL, 'sach', 'Viet', NULL, 'Y', 845000, 'Nuveen California Municipal Value Fund 2', 0, '2015/09/07');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (170, 69, 6, NULL, 'tapchi', 'Nga', 'Lua', 'Y', 280000, 'ARC Document Solutions, Inc.', 0, '2013/11/07');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (171, 8, 68, NULL, 'LA', 'Viet', 'Lua', 'Y', 330000, 'National Holdings Corporation', 0, '2008/12/28');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (172, 12, NULL, NULL, 'LA', 'Nga', NULL, 'Y', 874000, 'Maiden Holdings, Ltd.', 0, '2006/11/07');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (173, 4, 66, NULL, 'dia', 'Nga', 'Mem', 'Y', 316000, 'Alteryx, Inc.', 0, '2007/01/19');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (174, 50, NULL, NULL, 'dia', 'Trung', 'Mem', 'Y', 62000, 'Barclays Inverse US Treasury Composite ETN', 0, '2013/04/08');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (175, 26, 27, NULL, 'sach', 'Anh', 'Lua', 'Y', 649000, 'Alliance HealthCare Services, Inc.', 0, '2013/01/21');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (176, 37, NULL, NULL, 'LA', 'Trung', 'Cung', 'Y', 425000, 'Kemper Corporation', 0, '2014/11/12');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (177, 23, 21, 81, 'dia', 'Anh', 'Cung', 'Y', 415000, 'Nuveen Minnesota Quality Municipal Income Fund', 0, '2017/02/13');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (178, 1, 23, 32, 'dia', 'Nhat', 'Lua', 'Y', 249000, 'Amphenol Corporation', 0, '2012/02/08');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (179, 53, NULL, 16, 'LA', 'Viet', 'Lua', 'Y', 187000, 'First Trust RiverFront Dynamic Europe ETF', 0, '2005/10/22');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (180, 62, 4, NULL, 'sach', 'Anh', 'Mem', 'Y', 527000, 'Diana Shipping inc.', 0, '1994/02/09');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (181, 18, NULL, NULL, 'LA', 'Anh', 'Cung', 'Y', 285000, 'TravelCenters of America LLC', 0, '2001/05/08');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (182, 71, NULL, NULL, 'sach', 'Nhat', 'Mem', 'Y', 753000, 'Anworth Mortgage Asset  Corporation', 0, '1997/08/22');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (183, 78, NULL, NULL, 'sach', 'Anh', 'Cung', 'Y', 816000, 'MISONIX, Inc.', 0, '1994/08/31');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (184, 14, NULL, NULL, 'sach', 'Nhat', 'Mem', 'Y', 162000, 'Fanhua Inc.', 0, '2019/01/05');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (185, 46, NULL, NULL, 'LA', 'Trung', 'Mem', 'Y', 226000, 'Idera Pharmaceuticals, Inc.', 0, '2009/06/19');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (186, 92, 14, 80, 'LA', 'Viet', NULL, 'Y', 550000, 'First Trust Small Cap Growth AlphaDEX Fund', 0, '1999/06/15');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (187, 63, NULL, NULL, 'sach', 'Nga', 'Mem', 'Y', 95000, 'Algonquin Power & Utilities Corp.', 0, '1996/10/02');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (188, 12, 39, NULL, 'dia', 'Trung', 'Mem', 'Y', 88000, 'Caesarstone Ltd.', 0, '2007/06/21');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (189, 55, NULL, NULL, 'LA', 'Anh', 'Mem', 'Y', 218000, 'Oshkosh Corporation', 0, '2019/01/29');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (190, 9, 54, NULL, 'LA', 'Nga', 'Mem', 'Y', 816000, 'KKR & Co. L.P.', 0, '2018/02/07');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (191, 96, 29, NULL, 'dia', 'Anh', 'Cung', 'Y', 359000, 'Zogenix, Inc.', 0, '1991/06/27');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (192, 93, 16, NULL, 'sach', 'Nga', 'Lua', 'Y', 95000, 'PolarityTE, Inc.', 0, '2014/09/17');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (193, 80, 35, 34, 'dia', 'Nhat', NULL, 'Y', 264000, 'Nova Lifestyle, Inc', 0, '2019/07/09');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (194, 70, NULL, NULL, 'sach', 'Viet', 'Cung', 'Y', 675000, 'ChromaDex Corporation', 0, '1994/02/25');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (195, 76, NULL, NULL, 'sach', 'Trung', 'Mem', 'Y', 867000, 'Morgan Stanley', 0, '2019/01/23');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (196, 9, 43, NULL, 'dia', 'Viet', 'Lua', 'Y', 709000, 'Bellicum Pharmaceuticals, Inc.', 0, '2001/09/24');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (197, 62, NULL, NULL, 'sach', 'Nga', NULL, 'Y', 950000, 'Silgan Holdings Inc.', 0, '2016/03/10');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (198, 43, 19, NULL, 'sach', 'Nga', 'Lua', 'Y', 501000, 'Campbell Soup Company', 0, '2005/10/10');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (199, 77, NULL, 24, 'sach', 'Viet', 'Lua', 'Y', 235000, 'General Finance Corporation', 0, '2018/02/02');
insert into TaiLieu (ma_tailieu, ma_tacgia_1, ma_tacgia_2, ma_tacgia_3, ma_loai, ngonngu, bia, tinhtrang, gia, ten_tailieu, sl_kho, ngay_phathanh) values (200, 32, NULL, NULL, 'tapchi', 'Nhat', 'Lua', 'Y', 30000, 'KCG Holdings, Inc.', 0, '2017/02/11');
go
insert into ChiNhanh values ('SVH', N'Sư Vạn Hạnh');
insert into ChiNhanh values ('CT', N'Cao Thắng');
insert into ChiNhanh values ('TS', N'Thất Sơn');
insert into ChiNhanh values ('HM', N'Hóc Môn');
go
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (45, 1, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (114, 2, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (112, 3, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (177, 4, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (16, 5, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (162, 6, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (112, 7, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (71, 8, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (24, 9, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (112, 10, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (51, 11, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (89, 12, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (171, 13, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (65, 14, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (173, 15, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (98, 16, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (200, 17, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (69, 18, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (5, 19, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (52, 20, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (43, 21, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (84, 22, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (77, 23, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (66, 24, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (169, 25, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (173, 26, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (135, 27, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (167, 28, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (181, 29, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (53, 30, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (176, 31, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (76, 32, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (177, 33, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (151, 34, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (183, 35, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (75, 36, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (170, 37, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (118, 38, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (18, 39, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (178, 40, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (124, 41, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (192, 42, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (28, 43, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (62, 44, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (172, 45, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (147, 46, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (30, 47, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (136, 48, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (122, 49, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (184, 50, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (195, 51, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (171, 52, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (39, 53, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (74, 54, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (29, 55, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (63, 56, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (199, 57, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (90, 58, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (95, 59, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (55, 60, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (14, 61, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (162, 62, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (29, 63, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (2, 64, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (14, 65, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (67, 66, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (155, 67, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (125, 68, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (85, 69, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (157, 70, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (163, 71, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (13, 72, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (132, 73, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (138, 74, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (133, 75, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (40, 76, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (13, 77, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (95, 78, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (138, 79, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (173, 80, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (152, 81, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (55, 82, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (52, 83, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (77, 84, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (12, 85, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (88, 86, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (160, 87, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (22, 88, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (67, 89, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (192, 90, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (8, 91, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (189, 92, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (75, 93, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (134, 94, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (171, 95, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (66, 96, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (171, 97, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (147, 98, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (110, 99, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (159, 100, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (94, 101, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (79, 102, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (76, 103, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (174, 104, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (23, 105, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (126, 106, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (182, 107, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (169, 108, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (8, 109, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (6, 110, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (18, 111, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (53, 112, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (197, 113, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (166, 114, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (146, 115, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (89, 116, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (31, 117, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (35, 118, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (191, 119, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (163, 120, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (150, 121, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (31, 122, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (18, 123, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (144, 124, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (10, 125, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (44, 126, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (43, 127, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (156, 128, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (37, 129, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (18, 130, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (104, 131, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (90, 132, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (73, 133, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (144, 134, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (111, 135, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (122, 136, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (146, 137, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (110, 138, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (187, 139, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (56, 140, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (128, 141, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (81, 142, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (138, 143, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (55, 144, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (157, 145, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (138, 146, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (89, 147, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (132, 148, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (110, 149, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (80, 150, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (173, 151, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (20, 152, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (83, 153, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (112, 154, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (24, 155, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (167, 156, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (92, 157, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (51, 158, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (101, 159, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (121, 160, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (86, 161, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (157, 162, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (53, 163, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (79, 164, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (70, 165, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (59, 166, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (75, 167, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (11, 168, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (110, 169, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (158, 170, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (140, 171, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (84, 172, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (123, 173, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (173, 174, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (134, 175, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (114, 176, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (197, 177, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (157, 178, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (59, 179, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (50, 180, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (179, 181, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (88, 182, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (59, 183, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (22, 184, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (193, 185, 'CT', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (191, 186, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (124, 187, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (14, 188, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (87, 189, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (150, 190, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (176, 191, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (105, 192, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (74, 193, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (36, 194, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (122, 195, 'TS', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (179, 196, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (9, 197, 'SVH', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (104, 198, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (188, 199, 'HM', 'Y');
insert into BanSao (ma_tailieu, ma_bansao, ma_ChiNhanh, tinhtrang) values (152, 200, 'CT', 'Y');
go
insert into Quyen values ('admin', 'admin')
insert into Quyen values ('thuthu', 'thu thu')
insert into Quyen values ('nhanvien', 'nhan vien')
go
insert into NhanVien values('qltv_duy','admin','SVH','123',7601818331)
insert into NhanVien values('qltv_nghi','admin','SVH','123',7601818331)
insert into NhanVien values('qltv_bui','admin','SVH','123',7601818331)
insert into NhanVien values('qltv_hieu','admin','SVH','123',7601818331)
insert into NhanVien values('thuthusvh',	'thuthu','SVH','123',8121927041)
insert into NhanVien values('nhanvien1svh', 'nhanvien','SVH','123',1303538473)
insert into NhanVien values('nhanvien2svh', 'nhanvien','SVH','123',2398354903)
insert into NhanVien values('nhanvien3svh', 'nhanvien','SVH','123',8608050483)
go
insert into NhanVien values('admin1','admin','HM','123',2775584190)
insert into NhanVien values('thuthuhm','thuthu','HM','E8BIcr',1708390712)
insert into NhanVien values('nhanvien1hm','nhanvien','HM','DrwBM4KsZM8q',4646325571)
insert into NhanVien values('nhanvien2hm','nhanvien','HM','6jh9p2q2',9351399471)
insert into NhanVien values('nhanvien3hm','nhanvien','HM','PvvIxtY2bXXM',3096646547)
go
insert into NhanVien values('thuthuts', 'thuthu','TS','123',3614268786)
insert into NhanVien values('nhanvien1ts', 'nhanvien','TS','123',1692782990)
insert into NhanVien values('nhanvien2ts', 'nhanvien','TS','123',5856341472)
insert into NhanVien values('nhanvien3ts', 'nhanvien','TS','123',2238656437)
go
insert into NhanVien values('thuthuct','thuthu','CT','123',8121927041)
insert into NhanVien values('nhanvien1ct','nhanvien','CT','123',2619607813)
insert into NhanVien values('nhanvien2ct','nhanvien','CT','123',1787789016)
insert into NhanVien values('nhanvien3ct','nhanvien','CT','123',2559007735)
go
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('120-43-5323', 'Burde', '1994-12-14', '3756 Towne Point', '4973583014');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('688-75-2405', 'Child', '2012-06-18', '0447 Vahlen Hill', '6032505639');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('402-38-4301', 'Pickton', '1956-03-26', '977 Luster Crossing', '1665429886');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('334-44-1745', 'Ritchman', '1991-08-13', '35 Grayhawk Place', '1682408673');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('797-84-6467', 'Claypoole', '1959-05-04', '605 Corry Junction', '6697217556');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('318-96-7435', 'Van den Broek', '1961-12-10', '8874 Welch Lane', '6266645419');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('660-14-7653', 'Danielsky', '1957-09-20', '56535 Ohio Place', '7539611161');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('476-26-0596', 'Courtney', '1951-11-14', '53785 Warrior Alley', '6567518963');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('136-06-5377', 'Medgwick', '1947-08-13', '28 Forster Park', '1671737278');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('251-03-5239', 'Antognoni', '2001-11-25', '3715 Monterey Court', '4433312450');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('456-97-7576', 'Tinline', '2007-09-05', '47576 Barby Park', '4313786842');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('274-18-4480', 'Chalcraft', '2012-03-08', '64 Homewood Avenue', '3724911363');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('260-55-4932', 'Twitchett', '2013-10-02', '35 Bowman Crossing', '5953255877');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('525-57-9997', 'Crole', '1974-01-06', '26 Pine View Park', '8931266434');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('249-54-3453', 'Blakeley', '1963-06-03', '5066 La Follette Trail', '7506603245');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('585-60-7222', 'Grabert', '1968-10-13', '642 Blackbird Road', '1515293353');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('422-48-7374', 'Bultitude', '1962-01-10', '6302 Towne Trail', '2762557851');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('745-71-9286', 'Perett', '1997-11-03', '5 Mitchell Road', '4005754571');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('187-83-8027', 'Draxford', '2006-12-09', '3 Buhler Lane', '6253004146');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('581-33-9265', 'Mullenger', '1984-07-26', '842 Amoth Parkway', '2877267201');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('601-59-0495', 'Heinert', '1948-04-22', '471 Forest Run Court', '3119657079');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('826-42-8292', 'Canter', '1983-07-23', '31 Macpherson Lane', '7626094087');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('462-22-2911', 'Elvey', '1975-08-01', '1406 Waubesa Way', '4858683090');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('184-76-8718', 'Rooper', '1949-07-04', '5 Southridge Lane', '9732485166');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('326-96-4801', 'Clifft', '2004-04-01', '30679 Hansons Circle', '7992274931');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('802-63-0835', 'Badrock', '1966-02-21', '88470 Killdeer Way', '9174080784');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('185-97-2690', 'Ratchford', '1982-06-29', '16743 Bellgrove Terrace', '5467134741');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('353-16-7725', 'Bolsover', '1985-01-25', '6487 Susan Junction', '6432355268');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('517-73-7323', 'Bundey', '1992-07-26', '2 Warbler Hill', '5299382763');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('692-36-5023', 'Plan', '1956-04-07', '1223 Jay Circle', '7817824666');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('768-50-9228', 'Trustrie', '2011-09-30', '511 Ruskin Street', '9779325518');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('670-21-4672', 'Skeats', '1958-03-30', '6615 Ronald Regan Court', '9161397015');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('613-48-5781', 'Gulliver', '1957-12-18', '65 Ludington Park', '9007277108');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('143-33-4572', 'Thripp', '1960-07-08', '47526 1st Pass', '6372137219');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('499-07-5116', 'Miche', '1966-06-17', '32 Londonderry Court', '6042442211');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('432-34-1490', 'Catford', '1963-08-09', '291 Village Green Hill', '8012706844');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('754-07-1848', 'Rodger', '2009-07-12', '6854 Elmside Junction', '5466534054');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('499-78-6563', 'Reeman', '1996-01-30', '356 Milwaukee Drive', '8282289402');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('197-11-2785', 'Paoletto', '1991-03-11', '760 Messerschmidt Crossing', '3456007053');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('131-40-5817', 'Pickering', '1996-03-27', '71 Amoth Crossing', '3638140851');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('336-46-4891', 'Atmore', '2007-01-20', '2 Florence Street', '4758183910');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('395-81-2683', 'Lamberth', '1995-11-25', '037 Bashford Terrace', '9527535684');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('855-29-5916', 'Larway', '1951-04-25', '1364 Heath Trail', '8717227849');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('825-43-6895', 'Seakings', '1983-07-13', '2 Merrick Hill', '3702258992');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('693-25-6120', 'Arents', '1958-01-03', '93 Grasskamp Alley', '6001847913');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('356-59-6296', 'Klambt', '1990-02-04', '55212 Mcguire Place', '8121221896');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('507-12-8219', 'Seiffert', '1996-11-15', '49 Esker Way', '4897976051');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('554-68-7400', 'Jills', '2008-10-28', '4494 Oak Valley Terrace', '7132870067');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('342-01-5996', 'Freire', '1972-11-12', '133 Kingsford Parkway', '3422889087');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('614-76-1394', 'Bengefield', '1995-06-13', '449 Towne Trail', '7986607680');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('593-98-2448', 'Rawlcliffe', '1962-01-23', '77 Longview Street', '8474019831');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('220-62-5977', 'Piggot', '1965-05-30', '4608 Brickson Park Place', '7722430440');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('559-48-5938', 'Twopenny', '1990-06-23', '9 Nevada Hill', '8359970475');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('197-46-8546', 'McCrainor', '1980-04-15', '7279 Tennyson Drive', '1892843751');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('580-84-3776', 'Itzkovitch', '1985-10-24', '2186 International Court', '6889960056');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('194-32-4422', 'Treamayne', '2011-12-28', '82756 Russell Drive', '7621733866');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('338-96-4765', 'Sidden', '1968-11-06', '88 Summer Ridge Avenue', '4028608212');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('342-49-1840', 'Eblein', '2010-11-06', '21872 Emmet Point', '6627800770');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('401-04-5938', 'Garett', '1975-07-05', '58 Hoffman Hill', '4019840164');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('577-96-6320', 'Gebhardt', '1977-06-27', '15517 Coleman Parkway', '6092336516');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('434-17-5236', 'Guidone', '1992-01-23', '16 Gateway Pass', '6955379686');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('599-58-8737', 'Suddock', '2009-02-23', '550 Novick Circle', '8848682351');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('511-03-0468', 'Audiss', '1983-03-04', '9788 Brickson Park Avenue', '9001961625');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('369-71-8142', 'McKeever', '1996-09-03', '2 Ridgeview Junction', '2623105216');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('838-80-5858', 'Dunlap', '1978-03-24', '2 Morning Court', '3978231767');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('860-92-8365', 'Bifield', '1964-12-28', '495 Moulton Alley', '8805065677');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('759-04-4951', 'Letty', '1975-04-20', '9 Eliot Pass', '9345586810');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('439-87-7818', 'Bamblett', '1966-04-03', '2664 Hoepker Crossing', '4814794607');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('721-46-1663', 'Campos', '1975-06-11', '1 Glendale Way', '2548285958');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('250-31-0463', 'O''Cannovane', '1959-08-11', '2016 Grim Pass', '9968547409');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('586-82-6454', 'Colcutt', '1992-05-19', '348 Clarendon Circle', '2904109834');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('746-58-2298', 'Mackerness', '1971-10-27', '41219 Nobel Lane', '3779187552');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('396-75-3909', 'MacCallester', '1969-09-22', '6607 Vernon Parkway', '2578862797');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('660-93-7883', 'Chapier', '1979-01-15', '5 Anzinger Circle', '8372663385');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('280-82-4341', 'Paulley', '1998-12-08', '6385 Goodland Avenue', '6106224730');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('679-29-8035', 'Tidball', '1973-10-18', '565 Debs Plaza', '3792870442');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('138-31-6462', 'Batterson', '1989-10-03', '21 Onsgard Street', '5564084156');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('385-93-0776', 'Folker', '1981-03-12', '46 Westerfield Road', '4493981955');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('178-36-6615', 'Lardez', '1988-11-27', '439 Pine View Lane', '8339414953');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('116-90-7364', 'Pierson', '1989-05-09', '02625 Kropf Place', '6095007036');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('714-51-2098', 'Jurges', '1969-06-03', '2 Hazelcrest Terrace', '7448154741');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('877-79-4448', 'Sate', '1985-04-26', '553 Graceland Crossing', '4355790037');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('200-73-9037', 'Gerram', '2002-06-07', '92430 Old Gate Circle', '2723617072');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('711-11-9361', 'Stollhofer', '1963-07-06', '76673 Thompson Park', '8366326048');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('833-83-2667', 'Lehrian', '1952-01-19', '8 Hayes Park', '1157211594');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('512-14-5490', 'Blethyn', '1978-08-16', '1004 Fairview Park', '4715531702');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('697-53-0393', 'Mycock', '2008-12-24', '8 Hagan Crossing', '8942343515');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('654-64-7988', 'Corneliussen', '2010-03-28', '3 Elgar Court', '8686448206');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('204-74-3122', 'Huygen', '2008-07-01', '733 Sunnyside Drive', '7655172131');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('521-30-6379', 'Kiehl', '1992-06-03', '04750 Morrow Court', '7957314341');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('174-92-8934', 'Wooller', '2014-09-29', '8368 Duke Pass', '8201664996');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('112-11-1435', 'Duerden', '1963-05-07', '9544 Blue Bill Park Point', '9985157671');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('859-15-1083', 'Lowthian', '1979-07-30', '00 Pepper Wood Park', '4597597339');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('312-04-2730', 'Priddis', '1985-10-03', '5130 Sunbrook Trail', '8142614194');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('329-40-4059', 'Habben', '1948-01-12', '90 Karstens Terrace', '5364510204');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('464-95-6515', 'Webb', '1961-09-23', '52 Dapin Lane', '5958017834');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('882-14-4915', 'Glenister', '1979-03-02', '8 Porter Park', '9025572020');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('176-05-6777', 'Garriock', '1960-07-24', '7 4th Parkway', '4962330846');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('639-96-1208', 'Bernhart', '1997-12-29', '1 Village Green Point', '8839312574');
insert into DocGia (ma_sinhvien, hoten, NgaySinh, diachi, sdt) values ('657-75-2755', 'Vidgeon', '1972-05-29', '6219 Carberry Alley', '2433713997');
go
use master
drop login qltv_duy
drop login qltv_nghi
drop login qltv_bui
drop login qltv_hieu
go
create login qltv_duy with password='123'
create login qltv_nghi with password='123'
create login qltv_bui with password='123'
create login qltv_hieu with password='123'
go
use qltv
go
create user duy for login qltv_duy
create user nghi for login qltv_nghi
create user bui for login qltv_bui
create user hieu for login qltv_hieu
go
sp_addrolemember @rolename='db_owner', @membername='duy'
go
sp_addrolemember @rolename='db_owner', @membername='nghi'
go
sp_addrolemember @rolename='db_owner', @membername='bui'
go
sp_addrolemember @rolename='db_owner', @membername='hieu'
go